Traceback (most recent call last):
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/main.py", line 98, in <module>
    agent = make_agent(config["agent_type"], envs, config)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/agents/__init__.py", line 15, in make_agent
    return DRNDPPOAgent(envs, config)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/agents/drnd_ppo_agent.py", line 49, in __init__
    self.lam = config["gae_lambda"]
KeyError: 'gae_lambda'
